name: CI Example

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "**.go" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example:
    # Service containers are only supported on Linux runners
    runs-on: ubuntu-latest
    services:
      gittlz:
        image: karashiiro/gittlz:latest
        ports:
          - 6177:6177
          - 9418:9418
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Install
      run: go install .
    - name: Create new repo
      run: gittlz create-repo example
    - name: Clone new repo
      run: git clone git://localhost/example.git
