name: CI Example

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "**.go" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example:
    # Service containers are only supported on Linux runners
    runs-on: ubuntu-latest
    services:
      gittlz:
        # A Gittlz container, using the default Git protocool
        image: karashiiro/gittlz:0.3.0
        ports:
          - 6177:6177
          - 9418:9418
    steps:
    # Checkout your repository
    - uses: actions/checkout@v3
    # Install Go v1.19+
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    # Install the Gittlz CLI
    - name: Install Gittlz CLI
      run: go install github.com/karashiiro/gittlz@v0.3.0
    # Connect to the active service container via the CLI, and create
    # a new repository
    - name: Create new repo
      run: gittlz create-repo example
    # Clone the repository
    - name: Clone new repo
      run: git clone git://localhost/example.git
    # Do things with the repository...
